title:             pushgerm Tech
email:             mkk0618@gmail.com
description:       기록을 남기기 위해 시작한 기술 블로그
author:            Start Bootstrap
baseurl:           ""
url:               "http://pushgerm.github.io"

# Social Profiles
twitter_username:
github_username:   pushgerm
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
